#!/bin/bash

docker rm -f hackforthesea_www
docker run -it \
        -p 8000:8000 \
        --name hackforthesea_www \
        -v `pwd`:/usr/src/app \
        --hostname hackforthesea_www \
        hackforthesea/www:dev 
