# Generated by Django 2.0.5 on 2018-05-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_frequentlyaskedquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='location',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='team',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='hackathon',
        ),
        migrations.DeleteModel(
            name='Hackathon',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
