# Generated by Django 2.0.5 on 2018-05-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180523_1420'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrequentlyAskedQuestion',
        ),
    ]
