# Generated by Django 2.0.5 on 2018-05-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4ts_hackathon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryorganization',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiaryorganization',
            name='document',
            field=models.FileField(null=True, upload_to='beneficiary_logos/'),
        ),
    ]
