# Generated by Django 2.0.5 on 2018-05-23 14:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('h4ts_hackathon', '0002_auto_20180523_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeStatements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=320)),
                ('image', models.FileField(null=True, upload_to='challenge_imgages/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('start_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h4ts_hackathon.Hackathon')),
            ],
        ),
        migrations.RenameField(
            model_name='beneficiaryorganization',
            old_name='document',
            new_name='logo',
        ),
        migrations.AddField(
            model_name='challengestatements',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h4ts_hackathon.Hackathon'),
        ),
    ]
