# Generated by Django 2.0.5 on 2018-05-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h4ts_hackathon', '0003_auto_20180523_1420'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChallengeStatements',
            new_name='ChallengeStatement',
        ),
    ]
