# Generated by Django 2.0.5 on 2018-05-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4ts_hackathon', '0005_frequentlyaskedquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='unlocode',
            field=models.CharField(default='GLO', max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
