# Generated by Django 2.0.5 on 2018-05-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4ts_hackathon', '0006_hackathon_unlocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
