# Generated by Django 2.0.5 on 2018-05-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('h4ts_hackathon', '0007_hackathon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengestatement',
            name='beneficiary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='h4ts_hackathon.BeneficiaryOrganization'),
            preserve_default=False,
        ),
    ]
