# Generated by Django 2.0.5 on 2018-05-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4ts_hackathon', '0008_challengestatement_beneficiary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengestatement',
            name='beneficiary',
        ),
        migrations.AddField(
            model_name='challengestatement',
            name='beneficiary',
            field=models.ManyToManyField(to='h4ts_hackathon.BeneficiaryOrganization'),
        ),
    ]
