# Generated by Django 2.0.5 on 2018-05-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h4ts_hackathon', '0009_auto_20180524_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengestatement',
            old_name='beneficiary',
            new_name='beneficiaries',
        ),
    ]
