# Generated by Django 2.0.5 on 2018-05-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4ts_hackathon', '0014_dataset_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='note',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
