# Generated by Django 2.0.5 on 2018-05-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4ts_hackathon', '0016_auto_20180524_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='logo',
            field=models.FileField(null=True, upload_to='hackathon_logos/'),
        ),
    ]
