# Generated by Django 2.0.5 on 2018-05-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4ts_hackathon', '0017_hackathon_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purveyor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('logo', models.FileField(null=True, upload_to='sponsor_logos/')),
            ],
        ),
    ]
