# Generated by Django 2.0.5 on 2018-05-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4ts_hackathon', '0018_purveyor'),
    ]

    operations = [
        migrations.AddField(
            model_name='purveyor',
            name='in_footer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purveyor',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
