# Generated by Django 2.0.5 on 2018-08-31 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4ts_hackathon', '0020_auto_20180606_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='address',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hackathon',
            name='city',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hackathon',
            name='state',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hackathon',
            name='ticket_link',
            field=models.URLField(default='https://www.eventbrite.com/e/hack-for-the-sea-2018-tickets-45603855359'),
            preserve_default=False,
        ),
    ]
