# Generated by Django 2.0.5 on 2018-08-31 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('h4ts_hackathon', '0021_auto_20180831_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='hackathon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='h4ts_hackathon.Hackathon'),
            preserve_default=False,
        ),
    ]
